version: "2"

services:

  app:
    build: ./app
    volumes:
      - /var/run/php-fpm
      - ../web:/var/www/service
    user: centos
    working_dir: /var/www/service

  web:
    build: ./web
    volumes_from:
      - app
    ports:
      - 80:80
      - 443:443
    environment:
      SERVER_NAME: 192.168.99.100
      PHP_SOCKET: /var/run/php-fpm/php-fpm.sock
    command: sh -c "envsubst '$$SERVER_NAME $$PHP_SOCKET' < /etc/nginx/conf.d/concrete5.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  db:
    build: ./db
    volumes:
      - datastore:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql